# Generated by Django 4.1.7 on 2023-04-05 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_contactpage_delete_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactpage',
            old_name='subject',
            new_name='para',
        ),
    ]
