# Generated by Django 4.1.7 on 2023-04-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_rename_subject_contactpage_para'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zipcode', models.CharField(max_length=6)),
                ('ptype', models.CharField(default='Mens ware', max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('prange', models.CharField(default='₹100-₹500', max_length=30)),
                ('comment', models.CharField(max_length=30)),
            ],
        ),
    ]
