# Generated by Django 4.1.7 on 2023-04-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_title_wcstore_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wcstore',
            name='price',
            field=models.FloatField(),
        ),
    ]
